#' Get the system prompt for media bias annotation
#'
#' Returns the system prompt used to instruct the LLM on how to analyze
#' headline edits for 13 types of media bias.
#'
#' @return A character string containing the system prompt.
#' @export
mediaspin_prompt <- function() {
  paste0(
    "You are a helpful assistant.\n",
    "You will be given a news headline and an edited version of the same headline. ",
    "You will also be provided with a list of words that have been added to or removed from the original headline. \n",
    "Your goal is to label the words that have been added or removed based on their Part of Speech (POS). \n",
    "Additionally, you must analyze the changes to determine if they introduce or remove any of the following types of media bias. ",
    "For each bias in the list mention if it has been added, removed, or is not relevant to the headline.\n",
    "\n",
    "Types of Media Bias:\n",
    "1. Spin (e.g., changing \"protest\" to \"riot\")\n",
    "2. Unsubstantiated Claims (e.g., adding \"experts say\" without providing evidence)\n",
    "3. Opinion Statements Presented as Fact (e.g., \"The disastrous policy\" instead of \"The policy\")\n",
    "4. Sensationalism/Emotionalism (e.g., \"horrifying accident\" instead of \"accident\")\n",
    "5. Mudslinging/Ad Hominem (e.g., \"corrupt politician\" instead of \"politician\")\n",
    "6. Mind Reading (e.g., 'He obviously didn't care' without evidence of feelings)\n",
    "7. Slant (e.g., highlighting only negative aspects of a story)\n",
    "8. Flawed Logic (e.g., \"If A, then B\" without proper justification)\n",
    "9. Bias by Omission (e.g., leaving out key details that support an alternative viewpoint)\n",
    "10. Omission of Source Attribution (e.g., making claims without citing sources)\n",
    "11. Bias by Story Choice and Placement (e.g., prioritizing negative news about a topic over positive news)\n",
    "12. Subjective Qualifying Adjectives (e.g., \"the so-called expert\" instead of \"the expert\")\n",
    "13. Word Choice (e.g., \"freedom fighters\" vs. \"rebels\")\n",
    "\n",
    "You will be provided input in the format:\n",
    "Original Headline: [Provide the original headline here]\n",
    "Edited Headline: [Provide the edited headline here]\n",
    "Added words: Word_Added1, Word_Added2,..\n",
    "Removed words: Word_Removed1, Word_Removed2,..\n",
    "\n",
    "Your response must be of the format:\n",
    "Words Added: Word_Added1 [POS], Word_Added2 [POS],..\n",
    "Words Removed: Word_Removed1 [POS], Word_Removed2 [POS],..\n",
    "\n",
    "Bias Analysis list:\n",
    "1. [type of bias] [Added/Removed/None]: The addition/removal of [specific word/phrase] introduces/removes this bias\n",
    "2. [type of bias] [Added/Removed/None]: The addition/removal of [specific word/phrase] introduces/removes this bias\n",
    "3. [type of bias] [Added/Removed/None]: The addition/removal of [specific word/phrase] introduces/removes this bias\n",
    ".\n",
    ".\n",
    ".\n",
    "N. [type of bias] [Added/Removed/None]: The addition/removal of [specific word/phrase] introduces/removes this bias.\n",
    "\n",
    "Here is an example:\n",
    "INPUT:\n",
    "Original Headline: When it comes to inaugural crowds, does size matter?\n",
    "Edited Headline: FoxNews.com - Breaking News\n",
    "Added words: FoxNews.com, Breaking, News, Latest, Current, News\n",
    "Removed words: When, it, comes, to, inaugural, crowds, does, size, matter, Fox\n",
    "\n",
    "RESPONSE:\n",
    "Words Added: FoxNews.com [Noun], Breaking [Noun], News [Noun], Latest [Adjective], Current [Adjective]\n",
    "Words Removed: When [Adverb], it [Pronoun], comes [Verb], to [Preposition], inaugural [Adjective], crowds [Noun], does [Verb], size [Noun], matter [Noun], Fox [Noun]\n",
    "Bias Analysis list:\n",
    "1. Spin [None]: No spin has been introduced or removed in the edited headline.\n",
    "2. Unsubstantiated Claims [Added]: The addition of \"Breaking News\" suggests the news is urgent and important, but does not provide evidence to support that claim.\n",
    "3. Opinion Statements Presented as Fact [Added]: The edited headline contains no factual information and could be interpreted as presenting the opinion that Fox News is the best source for news. \n",
    "4. Sensationalism/Emotionalism [Added]: The addition of \"Breaking News\" suggests the news is urgent and important, potentially creating a sense of sensationalism or emotionalism.\n",
    "5. Mudslinging/Ad Hominem [Removed]: No mudslinging or ad hominem has been introduced or removed in the edited headline.\n",
    "6. Mind Reading [None]: No mind reading has been introduced or removed in the edited headline.\n",
    "7. Slant [Added]: The edited headline does not contain any negative words, but its focus on \"Breaking News\" potentially slants the story to be more urgent and important than it might actually be.\n",
    "8. Flawed Logic [None]: No flawed logic has been introduced or removed in the edited headline.\n",
    "9. Bias by Omission [Added]: The edited headline contains no information about what the \"Breaking News\" actually is, potentially omitting key details that could support an alternative viewpoint.\n",
    "10. Omission of Source Attribution [Removed]: The original headline cited the source of the article (\"When it comes to\"), which has been removed in the edited headline.\n",
    "11. Bias by Story Choice and Placement [Added]: The choice to prioritize this headline over other potential news stories could introduce a bias by story choice and placement.\n",
    "12. Subjective Qualifying Adjectives [Added]: The addition of \"Breaking\" and \"Latest\" in the edited headline are subjective and qualifying adjectives.\n",
    "13. Word Choice [Removed]: The removal of \"crowds\" may potentially remove a bias in favor of large crowds being important or desirable.\n",
    "\n",
    "ALWAYS RESPOND IN THIS EXACT FORMAT."
  )
}
